language: java
jdk:
- oraclejdk8
script: "./.ci/ci.sh"
env:
  global:
  - secure: MG6gIyYW6p7QkjmPVX76DbyPcIE09me+q2WDhXM+nbgNXbRw7XbWlarolAUBV6jqaWAN7xBdbvRLnSa21QMXEDN+pWu5ggeLDGnbPVGvWJWxA0tEVP/z9shb0FrhK9LETmxurx04ScGv1xIpY1KQJSFAPVqTRKuhS7z4YrwPxtI=
  - secure: WlgHKrWS5CuqTttok9873i2doGYhoitEwSUFxyiyCXKqgr3+gnWU+WNlGcLEk9Jt6drLds28Chnksmm+gDBND/SW7hkNA7g7INofcP2OQc3TTjG6uCRX1Bw+vrOK847S6JbdgBLdpmRRZh5MmQpdrAGGvR9J0a2V4ftI9B8BgY8=
  - secure: gasXPxiRWeG5NS9TpEd+nZYNQ/sPcdqGpHhISC2BS9f9gm7IkkRy9WIyw2NikCB/kWq/tzjnrYizTVGPeIUZZMXlefyZEy1uP26AbdhnEqVHkdxVn3V2xvzvjdy7+lVTr0nO+dr8AvnrmHPsWZgDY0mqhPXj4gg7xnu4noJl+dY=
  - secure: ZacPXhat5xOqGsz9J14rBFoBdfNR559UXFj+DpK2EXButzsHZVbLp3X6X1lQIoMi1Pg/UJSASP3mXTG8kD9Jzkk7WGjQ4/RivyuQWLH6wMLY45Fl45cR5xswLk305MF/DxRzvIYk1mJczxGZAGBbIe0BF11KdAInt/SUeHFHbrc=
  - secure: SJnz/eTRsaoN79mbHeNFxNul0GUV0+gJdHmvtdCAj82ORVwybbn0FpibMS+o30x/z6GE7HXIxsF6isFJS9/WU/76WSsO6Ll+hA0WWjZjZs5M9him6VYSyYXrvSa4XZF5LxCWH/o86mFIzHK+wgkjbgbLA4H1FF2CdDRau2o0MSw=
  - secure: ntxzCqK7gfg/OihOu8vjNtd9hXnV+hxpIkm9udnj4J6FoNwrFAM1mvrpwk8nTDV4cIdBAB8F3W5HOEArdcYqkLIucgv3A9eAHg5yGb275rFggMlHpFq+L6bXkBxU/lrJ5aVAbY7tbhsJtcJU6dF0UQ5zfNb8+RifcaWhAnnQU6M=
  - secure: qA0z2NTw7Ex4cr6UdORRRSfHofp9rCEaEIkzn0SyeXFYZ/TtixS/G3HwSR6hEKO3BN9+HMVXHJG/t307vMaZC+oduk1aDV5Qj5632oXxSDeBx9o9KUKlPgaJKX1nSakNYzSQ22PcDmuoJet/riAvFINkEvplEsMvJ31OiYkoZaU=
